//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.24 at 12:07:48 PM EET 
//


package it.polito.dp2.NFV.sol3.client1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="host1" use="required" type="{http://service.sol3.NFV.dp2.polito.it}EntityName" />
 *       &lt;attribute name="host2" use="required" type="{http://service.sol3.NFV.dp2.polito.it}EntityName" />
 *       &lt;attribute name="avg_through" use="required" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="avg_latency" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "performanceType")
public class PerformanceType {

    @XmlAttribute(name = "host1", required = true)
    protected String host1;
    @XmlAttribute(name = "host2", required = true)
    protected String host2;
    @XmlAttribute(name = "avg_through", required = true)
    protected float avgThrough;
    @XmlAttribute(name = "avg_latency", required = true)
    protected int avgLatency;

    /**
     * Gets the value of the host1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHost1() {
        return host1;
    }

    /**
     * Sets the value of the host1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHost1(String value) {
        this.host1 = value;
    }

    /**
     * Gets the value of the host2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHost2() {
        return host2;
    }

    /**
     * Sets the value of the host2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHost2(String value) {
        this.host2 = value;
    }

    /**
     * Gets the value of the avgThrough property.
     * 
     */
    public float getAvgThrough() {
        return avgThrough;
    }

    /**
     * Sets the value of the avgThrough property.
     * 
     */
    public void setAvgThrough(float value) {
        this.avgThrough = value;
    }

    /**
     * Gets the value of the avgLatency property.
     * 
     */
    public int getAvgLatency() {
        return avgLatency;
    }

    /**
     * Sets the value of the avgLatency property.
     * 
     */
    public void setAvgLatency(int value) {
        this.avgLatency = value;
    }

}
