//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.24 at 12:07:48 PM EET 
//


package it.polito.dp2.NFV.sol3.client1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="name" use="required" type="{http://service.sol3.NFV.dp2.polito.it}EntityName" />
 *       &lt;attribute name="memory" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="disk_storage" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="func_type" use="required" type="{http://service.sol3.NFV.dp2.polito.it}func_typeType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "vnftType")
public class VnftType {

    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "memory", required = true)
    protected int memory;
    @XmlAttribute(name = "disk_storage", required = true)
    protected int diskStorage;
    @XmlAttribute(name = "func_type", required = true)
    protected FuncTypeType funcType;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the memory property.
     * 
     */
    public int getMemory() {
        return memory;
    }

    /**
     * Sets the value of the memory property.
     * 
     */
    public void setMemory(int value) {
        this.memory = value;
    }

    /**
     * Gets the value of the diskStorage property.
     * 
     */
    public int getDiskStorage() {
        return diskStorage;
    }

    /**
     * Sets the value of the diskStorage property.
     * 
     */
    public void setDiskStorage(int value) {
        this.diskStorage = value;
    }

    /**
     * Gets the value of the funcType property.
     * 
     * @return
     *     possible object is
     *     {@link FuncTypeType }
     *     
     */
    public FuncTypeType getFuncType() {
        return funcType;
    }

    /**
     * Sets the value of the funcType property.
     * 
     * @param value
     *     allowed object is
     *     {@link FuncTypeType }
     *     
     */
    public void setFuncType(FuncTypeType value) {
        this.funcType = value;
    }

}
