//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.24 at 12:07:02 PM EET 
//


package it.polito.dp2.NFV.sol3.service;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://service.sol3.NFV.dp2.polito.it}linkType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="host" type="{http://service.sol3.NFV.dp2.polito.it}EntityName" minOccurs="0"/>
 *         &lt;element ref="{http://service.sol3.NFV.dp2.polito.it}hostsType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://service.sol3.NFV.dp2.polito.it}EntityName" />
 *       &lt;attribute name="nffg_name" type="{http://service.sol3.NFV.dp2.polito.it}EntityName" />
 *       &lt;attribute name="VNFT" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "linkType",
    "host",
    "hostsType"
})
@XmlRootElement(name = "nodeType")
public class NodeType {

    protected List<LinkType> linkType;
    protected String host;
    protected List<HostsType> hostsType;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "nffg_name")
    protected String nffgName;
    @XmlAttribute(name = "VNFT", required = true)
    protected String vnft;

    /**
     * Gets the value of the linkType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the linkType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLinkType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LinkType }
     * 
     * 
     */
    public List<LinkType> getLinkType() {
        if (linkType == null) {
            linkType = new ArrayList<LinkType>();
        }
        return this.linkType;
    }

    /**
     * Gets the value of the host property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHost() {
        return host;
    }

    /**
     * Sets the value of the host property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHost(String value) {
        this.host = value;
    }

    /**
     * Gets the value of the hostsType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hostsType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHostsType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HostsType }
     * 
     * 
     */
    public List<HostsType> getHostsType() {
        if (hostsType == null) {
            hostsType = new ArrayList<HostsType>();
        }
        return this.hostsType;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the nffgName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNffgName() {
        return nffgName;
    }

    /**
     * Sets the value of the nffgName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNffgName(String value) {
        this.nffgName = value;
    }

    /**
     * Gets the value of the vnft property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVNFT() {
        return vnft;
    }

    /**
     * Sets the value of the vnft property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVNFT(String value) {
        this.vnft = value;
    }

}
