//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.24 at 12:07:49 PM EET 
//


package it.polito.dp2.NFV.sol3.client2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="name" type="{http://service.sol3.NFV.dp2.polito.it}EntityName" />
 *       &lt;attribute name="source_node" use="required" type="{http://service.sol3.NFV.dp2.polito.it}EntityName" />
 *       &lt;attribute name="dest_node" use="required" type="{http://service.sol3.NFV.dp2.polito.it}EntityName" />
 *       &lt;attribute name="min_through" type="{http://www.w3.org/2001/XMLSchema}float" default="0" />
 *       &lt;attribute name="max_latency" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "linkType")
public class LinkType {

    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "source_node", required = true)
    protected String sourceNode;
    @XmlAttribute(name = "dest_node", required = true)
    protected String destNode;
    @XmlAttribute(name = "min_through")
    protected Float minThrough;
    @XmlAttribute(name = "max_latency")
    protected Integer maxLatency;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the sourceNode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceNode() {
        return sourceNode;
    }

    /**
     * Sets the value of the sourceNode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceNode(String value) {
        this.sourceNode = value;
    }

    /**
     * Gets the value of the destNode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestNode() {
        return destNode;
    }

    /**
     * Sets the value of the destNode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestNode(String value) {
        this.destNode = value;
    }

    /**
     * Gets the value of the minThrough property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public float getMinThrough() {
        if (minThrough == null) {
            return  0.0F;
        } else {
            return minThrough;
        }
    }

    /**
     * Sets the value of the minThrough property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setMinThrough(Float value) {
        this.minThrough = value;
    }

    /**
     * Gets the value of the maxLatency property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getMaxLatency() {
        if (maxLatency == null) {
            return  0;
        } else {
            return maxLatency;
        }
    }

    /**
     * Sets the value of the maxLatency property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxLatency(Integer value) {
        this.maxLatency = value;
    }

}
